// #ProjectConfig: generated by `mu migrate` from mu.json.
package mu

// Remote build cache lives on the loosh platform registry (akashic), under the
// shared loosh-industries/mu-cache repo — the same content-addressed action
// cache the akashic project pushes to. akashic requires a namespace/name repo,
// so a bare "mu" is rejected. Auth: `mu cache login registry.platform.loosh.cloud`
// with a push-capable snk_ PAT.
cache: {
	backends: [
		{type: "disk", path: "~/.mu/cache"}, {
			type:     "oci"
			registry: "registry.platform.loosh.cloud/loosh-industries/mu-cache"
			write:    false
		}]
	read_repair: true
	push: {
		registry:   "registry.platform.loosh.cloud"
		repository: "loosh-industries/mu-cache"
	}
}

// `mu build --publish <target>` pushes that target's outputs to the platform
// registry (akashic) as a first-class artifact under loosh-industries/<slug>,
// tagged by git sha + latest. Same auth as the cache push.
publish: {
	registry:   "registry.platform.loosh.cloud"
	repository: "loosh-industries"
}
toolchains: [{
	toolchain: "bb"
	from:      "scratch"
	config: {
		version: "1.12.216"
		url:     "https://github.com/babashka/babashka/releases/download/v1.12.216/babashka-1.12.216-macos-aarch64.tar.gz"
		sha256:  "91499b3f430038f9b40e433215256a6e5392942780dca9984d493d2bcca7055d"
	}
}, {
	toolchain: "go"
	from:      "scratch"
	config: {
		version:      "1.25.8"
		url:          "https://go.dev/dl/go1.25.8.darwin-arm64.tar.gz"
		sha256:       "c6547959f5dbe8440bf3da972bd65ba900168de5e7ab01464fbdc7ac8375c21c"
		strip_prefix: "go"
	}
}]
plugins: [
	{name: "go", script: "plugins/go"},
	{name: "lint", script: "plugins/lint"}]
targets: [{
	target:    "//cmd/mu"
	toolchain: "go"
	sources: ["go.mod", "go.sum", "cmd/mu/*.go", "internal/builtin/*.go", "internal/cas/*.go", "internal/cas/oci/*.go", "internal/config/*.go", "internal/coordinator/*.go", "internal/dag/*.go", "internal/plugin/*.go", "internal/sandbox/*.go", "internal/scratch/*.go"]
	config: {
		output:   "mu"
		pkg:      "./cmd/mu"
		trimpath: true
	}
}, {
	target:    "//lint/go-vet"
	toolchain: "lint"
	sources: ["cmd/mu/*.go", "internal/**/*.go"]
	config: command: ["go", "vet", "./..."]
}, {
	target:    "//lint/gofmt"
	toolchain: "lint"
	sources: ["cmd/mu/*.go", "internal/**/*.go"]
	config: {
		command: ["gofmt", "-l", "."]
		fix_command: ["gofmt", "-w", "."]
	}
}, {
	target:    "//lint"
	toolchain: "shell"
	kind:      "kit"
	sources: []
	deps: ["//lint/go-vet", "//lint/gofmt"]
	config: {
		command: ["true"]
		impure: false
	}
}]
