#!/usr/bin/env bb

;; File convergence plugin for mu.
;;
;; Converges files to a desired state: write content, set permissions,
;; create symlinks, or delete files. Designed to consume desired-state
;; targets generated by pudl (or written by hand).
;;
;; Config options:
;;   path     - destination file path (required)
;;   source   - source file to copy (mutually exclusive with content)
;;   content  - literal content to write (mutually exclusive with source)
;;   mode     - file permissions as octal string (e.g. "0644", default: "0644")
;;   symlink  - create a symlink to this target (mutually exclusive with source/content)
;;   absent   - if true, ensure the file does not exist (default: false)
;;   owner    - file owner (optional, requires privilege)
;;   group    - file group (optional, requires privilege)

(require '[cheshire.core :as json]
         '[clojure.string :as str])

(defn handle-discover []
  {"name"             "file"
   "version"          "0.1.0"
   "protocol_version" 1
   "consumes"         ["source:any"]
   "produces"         ["file"]
   "config_schema"    {"path"    {"type" "string"}
                       "source"  {"type" "string"}
                       "content" {"type" "string"}
                       "mode"    {"type" "string"  "default" "0644"}
                       "symlink" {"type" "string"}
                       "absent"  {"type" "boolean" "default" false}
                       "owner"   {"type" "string"}
                       "group"   {"type" "string"}}})

(defn target-short-name [target-name]
  (last (str/split target-name #"[:/]")))

(defn plan-absent [config path short]
  ;; Ensure file does not exist.
  {"actions"
   [{"id"         "remove"
     "command"    ["sh" "-c" (str "rm -f '" path "'")]
     "inputs"     {}
     "outputs"    []
     "depends_on" []
     "env"        {}
     "network"    false}]
   "declared_outputs" {}})

(defn plan-symlink [config path target short]
  ;; Create or update a symlink.
  {"actions"
   [{"id"         "symlink"
     "command"    ["sh" "-c" (str "mkdir -p \"$(dirname '" path "')\" && "
                                  "ln -sfn '" target "' '" path "'")]
     "inputs"     {}
     "outputs"    [path]
     "depends_on" []
     "env"        {}
     "network"    false}]
   "declared_outputs" {"file" path}})

(defn plan-write-content [config path content mode short]
  ;; Write literal content to file.
  (let [actions
        [{"id"         "write"
          "command"    ["sh" "-c" (str "mkdir -p \"$(dirname '" path "')\" && "
                                      "cat > '" path "' <<'__MU_EOF__'\n"
                                      content
                                      "\n__MU_EOF__")]
          "inputs"     {}
          "outputs"    [path]
          "depends_on" []
          "env"        {}
          "network"    false}
         {"id"         "chmod"
          "command"    ["chmod" mode path]
          "inputs"     {}
          "outputs"    []
          "depends_on" ["write"]
          "env"        {}
          "network"    false}]
        actions (cond-> actions
                  (get config "owner")
                  (conj {"id"         "chown"
                         "command"    ["chown"
                                      (str (get config "owner")
                                           (when-let [g (get config "group")] (str ":" g)))
                                      path]
                         "inputs"     {}
                         "outputs"    []
                         "depends_on" ["write"]
                         "env"        {}
                         "network"    false}))]
    {"actions"          actions
     "declared_outputs" {"file" path}}))

(defn plan-copy-source [config path source mode short sources]
  ;; Copy a source file to destination.
  (let [actions
        [{"id"         "copy"
          "command"    ["sh" "-c" (str "mkdir -p \"$(dirname '" path "')\" && "
                                      "cp '" source "' '" path "'")]
          "inputs"     {source source}
          "outputs"    [path]
          "depends_on" []
          "env"        {}
          "network"    false}
         {"id"         "chmod"
          "command"    ["chmod" mode path]
          "inputs"     {}
          "outputs"    []
          "depends_on" ["copy"]
          "env"        {}
          "network"    false}]
        actions (cond-> actions
                  (get config "owner")
                  (conj {"id"         "chown"
                         "command"    ["chown"
                                      (str (get config "owner")
                                           (when-let [g (get config "group")] (str ":" g)))
                                      path]
                         "inputs"     {}
                         "outputs"    []
                         "depends_on" ["copy"]
                         "env"        {}
                         "network"    false}))]
    {"actions"          actions
     "declared_outputs" {"file" path}}))

(defn handle-plan [req]
  (let [target   (get req "target")
        tgt-name (get target "name")
        sources  (get target "sources" [])
        config   (get target "config" {})
        short    (target-short-name tgt-name)
        path     (get config "path")
        mode     (get config "mode" "0644")]

    (when-not path
      (throw (ex-info "file plugin requires \"path\" in config" {})))

    (cond
      (get config "absent" false)
      (plan-absent config path short)

      (get config "symlink")
      (plan-symlink config path (get config "symlink") short)

      (get config "content")
      (plan-write-content config path (get config "content") mode short)

      (get config "source")
      (plan-copy-source config path (get config "source") mode short sources)

      ;; If a source file is listed in sources, copy the first one.
      (seq sources)
      (plan-copy-source config path (first sources) mode short sources)

      :else
      {"error" "file plugin requires one of: content, source, symlink, or absent"})))

(defn handle-request [req]
  (case (get req "method")
    "discover" (handle-discover)
    "plan"     (handle-plan req)
    {"error" (str "unknown method: " (get req "method"))}))

;; Main NDJSON loop
(loop []
  (when-let [line (read-line)]
    (let [req  (json/parse-string line)
          resp (handle-request req)]
      (println (json/generate-string resp))
      (flush)
      (recur))))
