// #ProjectConfig: generated by `mu migrate` from mu.json.
package mu

plugins: [{
	name: "cowsay"
	command: ["bb", "../../plugins/cowsay/plugin.bb"]
}]
targets: [{
	target:    "//hello:greeting"
	toolchain: "cowsay"
	sources: ["message.txt"]
	config: output: "greeting.txt"
}]
